### ISSUE TITLE
Composer.json File

### ISSUE THREAD

**Issue by matthewsherman** [leymannx/rebuild_cache_access#1]
Any chance of adding a composer.json file to the project with a type of "drupal-module"?  This will help to use composer to keep the module updated and in the right place.

Example:

```
"name": "drupal/memcache",
  "description": "High performance integration with memcache.",
  "type": "drupal-module",
  "homepage": "http://drupal.org/project/memcache",
  "support": {
    "issues": "https://www.drupal.org/project/issues/memcache"
  },
  "license": "GPL-2.0+",
  "require": { }
}
```

**Comment by leymannx** [comment]
I already put it on drupal.org in a [Sandbox](https://www.drupal.org/sandbox/koiwo/2935139) and plan to convert it to a full project as soon as possible. But review process may take very long.

Actually you simply can keep everything consistent by adding this module's git path under `"repositories": [],` in your project's `composer.json` like in the following snippet manually and after that simply call `$ composer require rebuild_cache_access`

    ...
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        },
        {
            "type": "package",
            "package": {
                "name": "rebuild_cache_access",
                "version": "1.0",
                "type": "drupal-module",
                "source": {
                    "url": "https://github.com/leymannx/rebuild_cache_access.git",
                    "type": "git",
                    "reference": "tags/8.x-1.0"
                }
            }
        },
        ...

**Comment by leymannx** [comment]
@matthewsherman Can you tell me if that worked for you and if yes :) close this issue ?

**Comment by matthewsherman** [comment]
THhat did work and put it in my modules folder as appropriate!  Thanks for the quick response!

**Comment by leymannx** [comment]
The project now can be installed regularly: `$ composer require drupal/rebuild_cache_access`
