### ISSUE TITLE
Submit module for full project review on drupal.org

### ISSUE THREAD

**Issue by karudonaldson** [leymannx/rebuild_cache_access#2]
Is there a reason why you haven't uploaded this as a legitimate project on d.o?

**Comment by leymannx** [comment]
I've already put it in a [sandbox](https://www.drupal.org/sandbox/koiwo/2935139) a month ago but haven't found the time yet to make it a full project and submit it for review. I'll leave this issue open and try to fix it within the next 10 days.

**Comment by leymannx** [comment]
First step done: https://www.drupal.org/project/rebuild_cache_access

Install with Composer: `$ composer require drupal/rebuild_cache_access``

Now I have to file it for review to be able to opt into security advisory coverage

**Comment by leymannx** [comment]
Currently being reviewed: https://www.drupal.org/project/projectapplications/issues/2944108
